# Generated by Django 2.0.5 on 2018-05-28 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='has_coupon',
            name='coupon_id',
        ),
        migrations.RemoveField(
            model_name='has_coupon',
            name='customer_id',
        ),
        migrations.DeleteModel(
            name='Has_coupon',
        ),
    ]
