# Generated by Django 2.0.5 on 2018-05-28 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180528_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_id', to='api.Customer'),
        ),
    ]
