# Generated by Django 2.0.5 on 2018-05-11 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teemo', '0002_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Has_coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_id', to='teemo.Coupon')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_id', to='teemo.Customer')),
            ],
        ),
    ]
